package cn.bangnongmang.service.service;

public interface OrderFarmerStateName {

	String FARMER_WAITTING_AUTH = "FARMER_WAITTING_AUTH";
	String FARMER_WAITTING_PAY = "FARMER_WAITTING_PAY";
	String FARMER_WAITTING_CHOOSE_FIELD = "FARMER_WATTING_CHOOSE_FIELD";
	String FARMER_WAITTING_GOT = "FARMER_WAITTING_GOT";
	String FARMER_GOT = "FARMER_GOT";
	String FARMER_WORKING = "FARMER_WORKING";
	String FARMER_TODAY_WORKING_STOP = "FARMER_TODAY_WORKING_STOP";
	String FARMER_WAITTING_SIZE_ENSURE = "FARMER_WAITTING_SIZE_ENSURE";
	String FARMER_WAITTING_DISTRIBUTE = "FARMER_WAITTING_DISTRIBUTE";
	String FARMER_TODAY_WORK_FINISHED = "FARMER_TODAY_WORK_FINISHED";
	String FARMER_ALL_FINISHED = "FARMER_ALL_FINISHED";
	String FARMER_CANCELED = "FARMER_CANCELED";
	String FARMER_AUTH_FAILED = "FARMER_AUTH_FAILED";
}
