set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324521,@no_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324519,@no_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324520,@no_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324523,@yes_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324557,@no_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324524,@no_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324525,@yes_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324586,@yes_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324587,@yes_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324589,@no_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324588,@no_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324591,@no_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324590,@no_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324592,@no_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324596,@no_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324598,@no_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324594,@no_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324593,@no_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324599,@no_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324584,@no_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324595,@no_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324597,@no_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324528,@yes_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324561,@no_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324563,@yes_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324560,@yes_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324565,@no_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324527,@no_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324564,@yes_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324526,@no_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324571,@no_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324570,@no_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324569,@yes_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324529,@yes_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324567,@yes_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324585,@no_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324553,@no_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324552,@no_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324547,@no_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324531,@no_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324545,@yes_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324546,@no_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324532,@yes_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324549,@no_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324551,@yes_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324548,@yes_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324550,@no_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324530,@yes_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324600,@yes_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324533,@yes_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324602,@no_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324605,@no_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324604,@no_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324534,@no_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324535,@no_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324601,@no_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324536,@yes_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324510,@yes_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324516,@yes_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324517,@yes_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324518,@yes_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324515,@no_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324537,@yes_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324538,@yes_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324539,@yes_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324540,@yes_id);
set @yes_id=(select id from option_detail where option_name='是');
set @no_id=(select id from option_detail where option_name='否');
insert into option_machine_model_mapping value (1482804954324542,@yes_id);