DROP TABLE IF EXISTS invite_friend;
CREATE TABLE invite_friend(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
uid BIGINT,
friend_phone VARCHAR(45),
create_time BIGINT,
method INT,
message VARCHAR(255)
)ENGINE=INNODB AUTO_INCREMENT=128299 DEFAULT CHARSET=utf8;